### ISSUE TITLE
Comet links don’t work in JustPlayer

### ISSUE THREAD

**Issue by mohammadm147** [g0ldyy/comet#107]
For some reason, I can’t get any comet links to play in JustPlayer but torrentio links work just fine. I’m not sure if this is a comet issue or not but I wanted to let you know.

**Comment by g0ldyy** [comment]
configuration issue on your side, works fine on my phone with JustPlayer

**Comment by mohammadm147** [comment]
Unfortunately, i’m using the elfhosted community version so I think I’m just screwed.

**Comment by g0ldyy** [comment]
it also works fine on my side with elfhosted community version

**Comment by g0ldyy** [comment]
update: it's not working only on elfhosted public instance, works fine on my local comet instance
I will talk to them about this issue

**Comment by g0ldyy** [comment]
@mohammadm147 VLC works fine, might be an issue with Just Player spamming requests before running the video stream

**Comment by g0ldyy** [comment]
elfhosted issue, might be fixed might not
