### ISSUE TITLE
Offcloud support for comet

### ISSUE THREAD

**Issue by arao** [g0ldyy/comet#109]
Comet is a great this, but those of who had offcloud as backup subscription, integrating in comet can be a great addition. It helps when RD goes down.

For reference TorrentIO also support offcloud.

**Comment by ragmehos** [comment]
https://github.com/g0ldyy/comet/issues/42#issuecomment-2227179919

**Comment by MrXT21** [comment]
> [#42 (comment)](https://github.com/g0ldyy/comet/issues/42#issuecomment-2227179919)

What's bullshit about their API? Torrentio, media fusion and knightcrawler managed it and they have all the details of the files listed when the links are displayed.

**Comment by g0ldyy** [comment]
> > [#42 (comment)](https://github.com/g0ldyy/comet/issues/42#issuecomment-2227179919)
> 
> What's bullshit about their API? Torrentio, media fusion and knightcrawler managed it and they have all the details of the files listed when the links are displayed.

you are welcome to make a pull request

**Comment by Blockr22** [comment]
Hey since RD is now EOL, any chance offcloud can be added in comet as an alternative plz ?
