### ISSUE TITLE
What is the IP used by Comet ?

### ISSUE THREAD

**Issue by th2j** [g0ldyy/comet#111]
When i use Comet in Stremio with real-debrid,
real-debrid doesn't show my ip but another one (like : 2a09:bac5:27ea:1282::1d8:7e),

Can you tell my why ?

So it is safe to use Comet with real-debrid ?

Thanks

**Comment by g0ldyy** [comment]
Yes it is safe to use. We just don't give the real client IP to Real-Debrid because it's not necessary.

**Comment by th2j** [comment]
Also if i launch a stream from comet and another with torrentio at the same time, real-debrid will see two IP used at the same time

**Comment by g0ldyy** [comment]
The IPs that appear on Real-Debrid are not the ones that are checked by RD for ban. They check the IPs that stream.
As long as you are watching in the same house (with same IP), you can use as many addons as you want at the same time.

**Comment by th2j** [comment]
Ok thanks

**Comment by aayushrautela** [comment]
I have a 25 mpbs upload speed at home, so if i want to share with someone(selfhosted) and use it myself(but without proxy to save on upload bandwidth) then rd will only 1 IP, right?

**Comment by g0ldyy** [comment]
no, 2

**Comment by aayushrautela** [comment]
> no, 2

What would be the 2nd IP? 1st one from my home network directly without proxy. And 2nd one?

**Comment by g0ldyy** [comment]
> > no, 2
> 
> What would be the 2nd IP? 1st one from my home network directly without proxy. And 2nd one?

yeah nvm my bad, if you friends are using the proxy it will be 1 ip only 👍
