### ISSUE TITLE
Streams failing on Android TV and Android phone

### ISSUE THREAD

**Issue by upstart77** [g0ldyy/comet#113]
Hello,

I have set up comet and jackett using docker compose on linux (using the compose file from the repo). 

I can successfully play some/many Real Debrid streams from my desktop browser (web.strem.io and app.strem.io) apart from the occasional audio not working and video not working. I understand those issues are related to the specific stream and some issue with stremio web.

On android tv and phone I can see the streams and select a stream as well. So jackett works and the connection to my comet server works as well.

My issue is that on my android tv (google tv), when I open a stream, I get this error: `ERROR_CODE_IO_NETWORK_CONNECTION_FAILED`

On my android phone (pixel 6a), when I open a stream, I get this error: `Oops, Player Error: Stremio encountered and error with this media`

I have tried clearing the cache/data and reinstalling the app. Reinstalling the addon. Restarting the server.
There are no server logs when I choose the stream on android. The stream just fails on the client side maybe.
Streams play well on android tv/phone and web using torrentio with RD.

Is there some kind of configuration error on the client side or the server side that I need to change to get this to work? I would very much love to use comet to proxy my RD streams

**Comment by g0ldyy** [comment]
configuration issue on your side

**Comment by DustyTurtleDip** [comment]
@upstart77 have you managed to fix your issue?

I have the same experience, all services seem to communicate between eachother, but when streaming from the Comet RD add-on, it simple fail, but I don't see your error messages.

I am also using a Google TV (Not the 4K one) and a Google Pixel 7Pro

I tried disabling the use of warp and zilean, but the same issue persist.

I noticed that when the comet add-on is installed, I can't use stremio web. (I guess this is expected?)

Playing stream from Torrentio and/or Prowlarr magnets also fail from Comet add-on, but Torrentio works well from other add-ons.

@g0ldyy I understand that it's probably an issue in our configuration, but do you have any idea where it could come from?

Mon fichier.ENV
[env.txt](https://github.com/user-attachments/files/16881496/env.txt)

Portion Comet dans mon compose :
[compose.txt](https://github.com/user-attachments/files/16881518/compose.txt)

**Comment by g0ldyy** [comment]
> @upstart77 have you managed to fix your issue?
> 
> I have the same experience, all services seem to communicate between eachother, but when streaming from the Comet RD add-on, it simple fail, but I don't see your error messages.
> 
> I am also using a Google TV (Not the 4K one) and a Google Pixel 7Pro
> 
> I tried disabling the use of warp and zilean, but the same issue persist.
> 
> I noticed that when the comet add-on is installed, I can't use stremio web. (I guess this is expected?)
> 
> Playing stream from Torrentio and/or Prowlarr magnets also fail from Comet add-on, but Torrentio works well from other add-ons.
> 
> @g0ldyy I understand that it's probably an issue in our configuration, but do you have any idea where it could come from?
> 
> Mon fichier.ENV [env.txt](https://github.com/user-attachments/files/16881496/env.txt)
> 
> Portion Comet dans mon compose : [compose.txt](https://github.com/user-attachments/files/16881518/compose.txt)

tu serve Comet avec un reverse proxy? envoie moi la config

**Comment by DustyTurtleDip** [comment]
> > @upstart77 have you managed to fix your issue?
> > I have the same experience, all services seem to communicate between eachother, but when streaming from the Comet RD add-on, it simple fail, but I don't see your error messages.
> > I am also using a Google TV (Not the 4K one) and a Google Pixel 7Pro
> > I tried disabling the use of warp and zilean, but the same issue persist.
> > I noticed that when the comet add-on is installed, I can't use stremio web. (I guess this is expected?)
> > Playing stream from Torrentio and/or Prowlarr magnets also fail from Comet add-on, but Torrentio works well from other add-ons.
> > @g0ldyy I understand that it's probably an issue in our configuration, but do you have any idea where it could come from?
> > Mon fichier.ENV [env.txt](https://github.com/user-attachments/files/16881496/env.txt)
> > Portion Comet dans mon compose : [compose.txt](https://github.com/user-attachments/files/16881518/compose.txt)
> 
> tu serve Comet avec un reverse proxy? envoie moi la config

Le reverse proxy est hosté par DSM (Synology).
La version de nginx est : version: nginx/1.23.1 
J'ai récupéré le fichier de configuration et gardé seulement les config pour Comet.
Voici le fichier Anomysé: 
[comet_proxy.txt](https://github.com/user-attachments/files/16907644/comet_proxy.txt)
J'ai aussi essayé : 
[comet_proxy 2.txt](https://github.com/user-attachments/files/16908254/comet_proxy.2.txt)


"curl -i http://192.168.1.237:8010/configure" et "curl -i https://comet.mondomaine.com/configure" retournent correctement le contenu du service web.
"openssl s_client -connect comet.mbcrew.ca:443 -showcerts" retourne bien mon certificat.

la recherche fonctionne, mais dès que je démarre un stream depuis stremio via l'addon comet, la video semble vouloir démarrer mais elle stop immédiatement.

J'ai essayé plusieur lecteur video, mais je n'arrive pas à obtenir de message d'erreur contrairement à upstart77.

Si tu as besoin de plus d'information, hésite pas, et surtout merci pour ton projet!

**Comment by DustyTurtleDip** [comment]
> > > @upstart77 have you managed to fix your issue?
> > > I have the same experience, all services seem to communicate between eachother, but when streaming from the Comet RD add-on, it simple fail, but I don't see your error messages.
> > > I am also using a Google TV (Not the 4K one) and a Google Pixel 7Pro
> > > I tried disabling the use of warp and zilean, but the same issue persist.
> > > I noticed that when the comet add-on is installed, I can't use stremio web. (I guess this is expected?)
> > > Playing stream from Torrentio and/or Prowlarr magnets also fail from Comet add-on, but Torrentio works well from other add-ons.
> > > @g0ldyy I understand that it's probably an issue in our configuration, but do you have any idea where it could come from?
> > > Mon fichier.ENV [env.txt](https://github.com/user-attachments/files/16881496/env.txt)
> > > Portion Comet dans mon compose : [compose.txt](https://github.com/user-attachments/files/16881518/compose.txt)
> > 
> > 
> > tu serve Comet avec un reverse proxy? envoie moi la config
> 
> Le reverse proxy est hosté par DSM (Synology). La version de nginx est : version: nginx/1.23.1 J'ai récupéré le fichier de configuration et gardé seulement les config pour Comet. Voici le fichier Anomysé: [comet_proxy.txt](https://github.com/user-attachments/files/16907644/comet_proxy.txt) J'ai aussi essayé : [comet_proxy 2.txt](https://github.com/user-attachments/files/16908254/comet_proxy.2.txt)
> 
> "curl -i http://192.168.1.237:8010/configure" et "curl -i https://comet.mondomaine.com/configure" retournent correctement le contenu du service web. "openssl s_client -connect comet.mondomaine.co:443 -showcerts" retourne bien mon certificat.
> 
> la recherche fonctionne, mais dès que je démarre un stream depuis stremio via l'addon comet, la video semble vouloir démarrer mais elle stop immédiatement.
> 
> J'ai essayé plusieur lecteur video, mais je n'arrive pas à obtenir de message d'erreur contrairement à upstart77.
> 
> Voici ce que me retourne le conteneur comet lorsque je reste attaché (Le warning est du au fait que j'ai temporairement désactivé flaresolver): [comet_compose_activity.txt](https://github.com/user-attachments/files/16909989/comet_compose_activity.txt)
> 
> Si tu as besoin de plus d'information, hésite pas, et surtout merci pour ton projet!
> 
> _**PS : Je viens de tester et je me rends compte que si je passe par "Stremio Web" c'est fonctionnel, mais le même lien ne fonctionne pas sur Android (TV et CELL)**_
> 
> J'ai fait un debugging de l'app Stremio sur mon Pixel 7Pro et voici ce que je peu fournir comme information supplémentaire, en espérant que ça puisse être utile.
> 
> [https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE](url)
> 
> Il y a une erreur qui mentionne que l'application cible Android 12 (version S+) ou plus et nécessite qu'un des flags FLAG_IMMUTABLE ou FLAG_MUTABLE soit spécifié à la création d'un PendingIntent. `java.lang.IllegalArgumentException: com.stremio.one: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. `
> 
> Plusieurs messages indiquent que libnative-filters.so n'est pas trouvé dans plusieurs emplacements. `libnative-filters.so not found on /data/app/.../lib/arm64 `
> 
> Erreurs liées à VLCVideoView et à la tentative de chargement d'un média. `VLCVideoView.updatePlaybackNotification(VLCVideoView.java:494) VLCVideoView.loadMedia(VLCVideoView.java:348) VLCVideoViewManager.loadMedia(VLCVideoViewManager.java:206) `
> 
> J'ai récupéré l'URL COMET que VLC (Stremio) sur android essaie de lire puis je l'ai collé dans mon browser chrome (UNIX) et le stream est fonctionnel. Pas certain que ça ait rapport, mais le protocol est http au lieu de https. ![Screenshot from 2024-09-06 17-18-35](https://private-user-images.githubusercontent.com/38813688/365310573-daacf400-e1d8-40b1-b0dc-27380eb2ea43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NTk2NDEsIm5iZiI6MTcyNTY1OTM0MSwicGF0aCI6Ii8zODgxMzY4OC8zNjUzMTA1NzMtZGFhY2Y0MDAtZTFkOC00MGIxLWIwZGMtMjczODBlYjJlYTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDIxNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NTEwZDMzZDkyOTVmMzU1NTg0ODJiM2VjMTI2ZWE4YTY3YjYzNmYyMzY3ZGJkMzhjNjEwYjIxOWJiOTU4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfmyO1bkEgOsWdGRdbgY5wt9aFj6ThDxCizoHS0_0_M)

Finalement je confirme, le problème est l'utilisation de http au lieu de https. En ouvrant 80 vers comet, tout fonctionne. (Ça ne me semble pas viable comme solution)

**Comment by g0ldyy** [comment]
ah oui ça c'est logique aucun addon Stremio ne fonctionne en http 😅

**Comment by DustyTurtleDip** [comment]
> ah oui ça c'est logique aucun addon Stremio ne fonctionne en http 😅

C'est une modification à faire dans ton projet ou dans ma configuration selon toi?

**Comment by g0ldyy** [comment]
> > ah oui ça c'est logique aucun addon Stremio ne fonctionne en http 😅
> 
> C'est une modification à faire dans ton projet ou dans ma configuration selon toi?

dans ta config

**Comment by DustyTurtleDip** [comment]
> > > ah oui ça c'est logique aucun addon Stremio ne fonctionne en http 😅
> > 
> > 
> > C'est une modification à faire dans ton projet ou dans ma configuration selon toi?
> 
> dans ta config

Bon, quand même étrange que les autres add-ons renvoient des url https. Je vais continuer à chercher d'où ça peut venir!

Merci !
