### ISSUE TITLE
Sort by language or deselect Multi_Audio

### ISSUE THREAD

**Issue by XDeadHackerX** [g0ldyy/comet#116]
Good @g0ldyy , my congratulations for this spectacular Addon, it is clean and extracts a lot of possibilities to watch a Movie/Series.

I want to report a small error that the addon commits and that makes its use uncomfortable for older people. In the “Languages” section I unselect everything and select Spanish (thanks for taking into account our community) but when I try to watch a TV Show I get a lot of multilanguage results and I have to scroll down until I get results in my language. It is curious that this happens because I have unchecked the Multi_Audio and Dual_Audio option.

I would be very grateful if you could take a look to see if there is a solution or at least to order the results by language and the results in Spanish first and then the rest of the results.

Thank you very much for everything.
![imagen](https://github.com/user-attachments/assets/528c5707-9eb5-4916-a9b6-db404815a67f)

**Comment by g0ldyy** [comment]
Hey!
This will be fixed when @dreulavelle finish implementing [Parsett](https://github.com/dreulavelle/PTT) into [RNT](https://github.com/dreulavelle/rank-torrent-name), the module we're using for the title parsing!

At moment, disabling Multi_Audio and Dual_Audio does nothing.

**Comment by Zaarrg** [comment]
@XDeadHackerX You can give [comet-uncached](https://github.com/Zaarrg/comet-uncached) a try until its implemented. Has language prioritization and language search to search in other languages

**Comment by XDeadHackerX** [comment]
> > Good @g0ldyy , my congratulations for this spectacular Addon, it is clean and extracts a lot of possibilities to watch a Movie/Series.
> > I want to report a small error that the addon commits and that makes its use uncomfortable for older people. In the “Languages” section I unselect everything and select Spanish (thanks for taking into account our community) but when I try to watch a TV Show I get a lot of multilanguage results and I have to scroll down until I get results in my language. It is curious that this happens because I have unchecked the Multi_Audio and Dual_Audio option.
> > I would be very grateful if you could take a look to see if there is a solution or at least to order the results by language and the results in Spanish first and then the rest of the results.
> > Thank you very much for everything. ![imagen](https://private-user-images.githubusercontent.com/57367532/361759472-528c5707-9eb5-4916-a9b6-db404815a67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTc3NTcsIm5iZiI6MTcyNTExNzQ1NywicGF0aCI6Ii81NzM2NzUzMi8zNjE3NTk0NzItNTI4YzU3MDctOWViNS00OTE2LWE5YjYtZGI0MDQ4MTVhNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE1MTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWMyZmEzZTU1Yzc3ZjJiODhkNTQ1YjNlZDRjMjhmYjAwMjUyMmZmMmY0ZTI0ZmE0MWMwZGQ3ZTZjMmI3NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TvmTdAEFE8IhEAo-PCNDDsKcmvDM1pKa88baQdhweOY)
> 
> should be good now on latest image

Works Perfect!!!  Thank you very much for fixing that point now only shows the torrents in the indicated language. Thank you very much.

P.S.: Yesterday I was studying how good are the results in my language (Spanish) and I ran into a very annoying problem that has always haunted the Spanish community, I will explain in a new issue.
