### ISSUE TITLE
Torbox show invalid api key

### ISSUE THREAD

**Issue by ericvlog** [g0ldyy/comet#126]
hello, I just try out torbox using comet elfhosted, but it show invalid key.

the api I get from torbox setting pages.

thanks

**Comment by g0ldyy** [comment]
make sure you didn't put a space before entering it on the config page

**Comment by ericvlog** [comment]
I use the copy api button, and check font and end of api key to make sure no have space.

![image](https://github.com/user-attachments/assets/6a232a51-0b2d-47bc-b51d-871d69ece7cf)
![image](https://github.com/user-attachments/assets/4b1d1564-43f6-4fe0-9000-aa7e6f08b435)

**Comment by ericvlog** [comment]
hello, forget about it, i just register to try out torbox, 

beside this, now i get this error on my selfhosted comet.

```
2024-08-28 16:35:21 | ⚠️ WARNING | stream.stream - Exception while getting metadata for tt0117998: Cannot connect to host v3.sg.media-imdb.com:443 ssl:default [Try again]
2024-08-28 16:35:21 | 👾 API | main.dispatch - GET /eyJpbmRleGVycyI6WyJydXRvciIsIm1lam9ydG9ycmVudCIsInJ1dHJhY2
```
from comet selfthostd addon `can't get metadata for tt12345`

**Comment by g0ldyy** [comment]
> hello, forget about it, i just register to try out torbox,
> 
> beside this, now i get this error on my selfhosted comet.
> 
> ```
> 2024-08-28 16:35:21 | ⚠️ WARNING | stream.stream - Exception while getting metadata for tt0117998: Cannot connect to host v3.sg.media-imdb.com:443 ssl:default [Try again]
> 2024-08-28 16:35:21 | 👾 API | main.dispatch - GET /eyJpbmRleGVycyI6WyJydXRvciIsIm1lam9ydG9ycmVudCIsInJ1dHJhY2
> ```
> 
> from comet selfthostd addon `can't get metadata for tt12345`

the machine you're hosting Comet on can't access https://v3.sg.media-imdb.com, nothing I can really do

**Comment by ericvlog** [comment]
> > hello, forget about it, i just register to try out torbox,
> > beside this, now i get this error on my selfhosted comet.
> > ```
> > 2024-08-28 16:35:21 | ⚠️ WARNING | stream.stream - Exception while getting metadata for tt0117998: Cannot connect to host v3.sg.media-imdb.com:443 ssl:default [Try again]
> > 2024-08-28 16:35:21 | 👾 API | main.dispatch - GET /eyJpbmRleGVycyI6WyJydXRvciIsIm1lam9ydG9ycmVudCIsInJ1dHJhY2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from comet selfthostd addon `can't get metadata for tt12345`
> 
> the machine you're hosting Comet on can't access https://v3.sg.media-imdb.com, nothing I can really do

just today before update the docker still can, after update it fail, below is some of my test from machine hosted.

```
plsharevme@debian:~/appdata/comet$ curl -I https://v3.sg.media-imdb.com
HTTP/2 404
content-type: application/octet-stream
content-length: 0
server: awselb/2.0
date: Wed, 28 Aug 2024 16:41:37 GMT
cache-control: max-age=86400
x-cache: Error from cloudfront
via: 1.1 c837fad33cdc26548614f8e2b4b2b268.cloudfront.net (CloudFront)
x-amz-cf-pop: HKG62-C2
x-amz-cf-id: YN2XfSuwD1Hja9SZNdoVeMiXfNWR0VRqZg9vYZUy6N9wioUEM6YItA==
age: 2678

plsharevme@debian:~/appdata/comet$ ping https://v3.sg.media-imdb.com
ping: https://v3.sg.media-imdb.com: Name or service not known
plsharevme@debian:~/appdata/comet$ ping v3.sg.media-imdb.com
PING v3.sg.media-imdb.com(2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1)) 56 data bytes
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=1 ttl=58 time=40.7 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=2 ttl=58 time=40.7 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=3 ttl=58 time=41.3 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=4 ttl=58 time=40.8 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=5 ttl=58 time=40.6 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=6 ttl=58 time=43.0 ms
64 bytes from 2600:9000:2200:5800:f:2ac1:d3c0:93a1 (2600:9000:2200:5800:f:2ac1:d3c0:93a1): icmp_seq=7 ttl=58 time=40.5 ms
^C
--- v3.sg.media-imdb.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6008ms

```
It have reply.

**Comment by g0ldyy** [comment]
again, not a Comet issue but most likely a configuration issue on your side
works fine on the 3 VPS I just tried

**Comment by ericvlog** [comment]
> again, not a Comet issue but most likely a configuration issue on your side works fine on the 3 VPS I just tried

Okay thanks for your help, maybe i should reconfiguration it,

**Comment by g0ldyy** [comment]
are you proxying the docker container with glueton or something? (if you're using docker)

**Comment by ericvlog** [comment]
> are you proxying the docker container with glueton or something? (if you're using docker)

before i have use warp but i already disable it,

**Comment by ericvlog** [comment]
it okay can working now, I just restart server & flushdns .

so sorry troublesome.

**Comment by g0ldyy** [comment]
great!
