### ISSUE TITLE
Seeking in Stremio when using the proxy regenerates the url link in real debrid which eventually leads to rate limiting

### ISSUE THREAD

**Issue by pkonecki** [g0ldyy/comet#127]
When seeking in Stremio using the streaming proxy, the RD download link is regenerated each time:
![image](https://github.com/user-attachments/assets/761348d5-f32a-446b-a400-dfa41f55b55d)

This eventually leads to a warning which I guess is due to rate limiting:
`comet  | 2024-08-29 10:57:09 | ⚠️ WARNING | realdebrid.generate_download_link - Exception while getting download link from Real-Debrid for 78ffxxxxxxxxxxxxxxxx|1: 'uri'`

The result is that the video doesn't resume after a certain number of seeks.

**Comment by pkonecki** [comment]
I think the issue is related to this line:
`f"SELECT link, timestamp FROM download_links WHERE debrid_key = '{config['debridApiKey']}' AND hash = '{hash}' AND file_index = '{index}'"
`
In my config, debridapikey is empty because I want to use the proxy and not provide my api key in the addon config.
However the download link gets  cached with the api key because of this code:
`            if (
                settings.PROXY_DEBRID_STREAM
                and settings.PROXY_DEBRID_STREAM_PASSWORD
                == config["debridStreamProxyPassword"]
                and config["debridApiKey"] == ""
            ):
                config["debridService"] = (
                    settings.PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE
                )
                config["debridApiKey"] = (
                    settings.PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY
                )`
I guess the fix would be to do the same for getting the cached download link in the first place.

**Comment by g0ldyy** [comment]
working on a fix 👍

**Comment by g0ldyy** [comment]
@pkonecki fixed in latest commit, can you confirm?

**Comment by g0ldyy** [comment]
petite erreur de ma part 💀

**Comment by pkonecki** [comment]
Working flawlessly! Merci !
