### ISSUE TITLE
Separate Latin Language from Spanish

### ISSUE THREAD

**Issue by XDeadHackerX** [g0ldyy/comet#135]
Good morning again, 

Sorry to write another issue, I do not like to give work to developers but yesterday I was testing Comet configured with the language “Spanish” and most of the results that appeared with the flag of Spain really the audio is Latin 🇲🇽. I was looking at the name of the torrents and in most of them it says LATINO.

I know this is a delicate issue and many torrent sites classify the latin torrents as Spanish, but if you could do something to solve this problem our community would be very grateful.

In case it is a complicated task I can think of two possible solutions to reduce the results, although I don't know if these solutions are feasible.
1º) In the Spanish language Remove the results of the provider “Cinecalidad” since all of them are in Latin.
2º) Use regular expressions in the name of the torrent and thus filter it, if it takes “SPA” to appear in the results of Spanish, if it takes “LATINO or LATIN” to appear in the Latin language.

Thank you very much for such a great Addon and its public hosting.

![imagen](https://github.com/user-attachments/assets/10254ab1-a9c6-4667-902c-4c2485a28d77)

**Comment by g0ldyy** [comment]
@dreulavelle what do you think about that?

**Comment by dreulavelle** [comment]
I can see what I can do. What exactly are you looking for though? Differentiating Spanish from Latin?

**Comment by dreulavelle** [comment]
Oh I see, just need to separate the Latino rehex from the Spanish one. That's an easy fix. 

I can add the group you mentioned to for Spanish as well

**Comment by dreulavelle** [comment]
To help me improve the regex, torrent titles help me the most! If you have other issues, please be sure to include a snippet of torrent names and the desired result. Then I can add changes and create tests to ensure everything is working beautifully.  :)

**Comment by XDeadHackerX** [comment]
Nice to meet you @dreulavelle, indeed my idea is to separate the two languages, Spanish (🇪🇸) and Latin (🇲🇽), this way the people who want to use Comet to see content in Latin will select the flag “🇲🇽” and the Spaniards who want to see the content in Spanish will choose this “🇪🇸”. Next I am going to put you some of the regular expressions used by the creators of the torrent titles.

Spanish(🇪🇸): Esp, esp, Spa, spa, SPANISH, SPANiSH, Spanish, spanish

Latino(🇲🇽): Lat, lat, LATINO, Latino, latino, latino, LATIN, Latin, latin.

In principle there are no more options, thank you very much for taking into account this annoying error, thanks to these changes to the Spanish community will only appear results in our language and Latinos in theirs. I will be attentive to the changes in case I missed something.

Thanks guys!

**Comment by dreulavelle** [comment]
Isn't `latin` its own language thats separate from `latino` ?

**Comment by dreulavelle** [comment]
Alright, this has been fixed! :)

**Comment by dreulavelle** [comment]
Ah shit.. lol just noticed you mentioned `mx` as the language code.. and I used `la` haha.. will fix! 😅

**Comment by XDeadHackerX** [comment]
Thank you very much @dreulavelle, this is a great change for our community, when @g0ldyy applies the changes I will do some tests to study how it works and if any latin torren escapes.

"Isn't latin its own language thats separate from latino ?" Yes, the latin and the latino are diferents lenguages, but sometimes the torrents creatos use this name to refer to latino idiom

**Comment by g0ldyy** [comment]
> Thank you very much @dreulavelle, this is a great change for our community, when @g0ldyy applies the changes I will do some tests to study how it works and if any latin torren escapes.
> 
> "Isn't latin its own language thats separate from latino ?" Yes, the latin and the latino are diferents lenguages, but sometimes the torrents creatos use this name to refer to latino idiom

https://github.com/g0ldyy/comet/commit/24216678b8fca0ab8edd48d239fb772f06712b5f 👀

**Comment by XDeadHackerX** [comment]
> > Thank you very much @dreulavelle, this is a great change for our community, when @g0ldyy applies the changes I will do some tests to study how it works and if any latin torren escapes.
> > 
> > "Isn't latin its own language thats separate from latino ?" Yes, the latin and the latino are diferents lenguages, but sometimes the torrents creatos use this name to refer to latino idiom
> 
> https://github.com/g0ldyy/comet/commit/24216678b8fca0ab8edd48d239fb772f06712b5f 👀 

Thank you very much and very funny the emoji representing the "Latino" language 😂😂💃.

Could you upload the mods to the free elfhosted stay so I can test it. Thanks.

**Comment by g0ldyy** [comment]
> > > Thank you very much @dreulavelle, this is a great change for our community, when @g0ldyy applies the changes I will do some tests to study how it works and if any latin torren escapes.
> > > "Isn't latin its own language thats separate from latino ?" Yes, the latin and the latino are diferents lenguages, but sometimes the torrents creatos use this name to refer to latino idiom
> > 
> > 
> > [2421667](https://github.com/g0ldyy/comet/commit/24216678b8fca0ab8edd48d239fb772f06712b5f) 👀
> 
> Thank you much @g0ldyy , and very funny the emoji representing the "Latino" language 😂😂💃.
> 
> Could you upload the mods to the free elfhosted stay so I can test it. Thanks.

done, added to the public instance :)

**Comment by XDeadHackerX** [comment]
@

> Alright, this has been fixed! :)

Good again @dreulavelle, I forgot to put you 2 regular expressions used in Spanish torrents, these are:  Castellano, castellano.
Thank you very much for your work.
