### ISSUE TITLE
Add Wolfmax4 and MejorTorrent 

### ISSUE THREAD

**Issue by XDeadHackerX** [g0ldyy/comet#138]
I am testing the private version of Comet in ElfHosted, to my surprise the Proxy option is separate so I would have to pay 9€ + 9€ = 18€ to use this functionality. 

I am considering to take both options to share it with my family, but to do so I need Comet to give good results in Spanish and try to eliminate the Latin options. I have seen that Comet has the Torrentio scraper, it really solves the problem with Spanish, but after several tests I see that despite using Torrentio it does not use the Wolfmax4 and MejorTorrent libraries.

I would like to propose you to add them and so I will choose Comer privado as my only addon.

Thank you.

**Comment by funkypenguin** [comment]
Representing ElfHosted here.. If you had a private Comet, you could pick which indexers you wanted to use, if you supplied your own Jackett. However, that'd end up as 9€ + 9€ + 9€ = 27€ :( 

As an alternative.. there's a community Comet ("cometa"?) being worked on by Hayduk, and once the MediaFlow proxy is supported by comet, you'll be able to use a public comet instance with a private MediaFlow instance for ProxyStreaming (so total 9€)
