### ISSUE TITLE
Issue with Addon detecting wrong show

### ISSUE THREAD

**Issue by Raislog** [g0ldyy/comet#139]
When searching for TV series Slow Horses (any season/episode) comet sends a search to the indexer for 'Primetime Emmys'. This was verified in Jackett logs, and Comet docker logs. Also confirmed it searches Zilean for Primetime Emmys

I have other addons that are correctly detecting the show and displaying results.

**Comment by g0ldyy** [comment]
fixed https://github.com/g0ldyy/comet/commit/23966f22887e1d744f2342a97d7b39652155ddb1
