### ISSUE TITLE
Add support for rlsbb ddls

### ISSUE THREAD

**Issue by oathzed** [g0ldyy/comet#142]
Can you please add DDL support to the scraper, debrid services can turn them into direct download links, just like torrents. Here is reference for the working scraper for a different app:

https://github.com/lalitjoshi06/Scrapers/blob/main/en_DebridOnly/rlsbb.json

Thank you!

**Comment by g0ldyy** [comment]
can't even access the website.

**Comment by oathzed** [comment]
> can't even access the website.

Try any of these:

http://rlsbb.ru/
https://rlsbb.to/

**Comment by oathzed** [comment]
If you still can't access any of those. Can you add support for this site? It's similar: psychodownloads.com
