### ISSUE TITLE
Docker network IP sent to RD

### ISSUE THREAD

**Issue by Raislog** [g0ldyy/comet#145]
Self Hosted / Latest version

Assuming its in relation to the below change:
https://github.com/g0ldyy/comet/commit/479aa8e527ebfeec01ffcde5c825b0a5af19538e

Before this change RD displayed the IP address of the addon/host. My assumption was the above was going to change the IP forwarded to RD to be the 'client'/streaming IP address. Similar to how some other addons do (torrentio/Annatar - last time I checked). I know this isn't required, but was requested by other users. 
My issue is that RD isn't reporting the Public IP address of the addon host OR the ip address of my clients. Its actually reporting an internal Docker Network IP. In my case its reporting the docker network IP address of my reverse proxy. 

Ex:
VPS host ip 165.xxx.xxx.xxx
Client host 107.xxx.xxx.xxx
Docker network 172.xxx.xxx.xxx

I could probably set up a x-forwarded-for rule on the proxy to see if I can fix this in config, but wanted to report it first to see if the current implementation would remain.

**Comment by g0ldyy** [comment]
you have to setup your reverse proxy correctly yes.

**Comment by Raislog** [comment]
Thanks for confirming - 

I updated config and used whoami to verify that the correct IP is being reported in X-FORWARDED-FOR and X-REAL-IP

rebooted addon and all is working as expected.
