### ISSUE TITLE
Add configuration option to enable admin to choose whether to pass Comet or client IP to Real Debrid

### ISSUE THREAD

**Issue by saulchristie** [g0ldyy/comet#150]
Due to public demand(?), commit 479aa8e527ebfeec01ffcde5c825b0a5af19538e changed Comet behaviour such that the streaming client IP was passed to Real Debrid instead the IP address of the Comet server itself.

A side effect of this is that in cases where `PROXY_DEBRID_STREAM` is used performance problems can occur if an end user is far-away from the Comet server and RD links get generated pointing to content local to the user, but a long distance from Comet for its proxying.

e.g. consider a user in Australia using a Comet proxy in Europe - such a setup gives a Sydney-Europe-Australia roundtrip instead of just Europe-Australia. This can make playback unstable in poor peering scenarios.

It would be advantageous for Comet hosters to be able to choose whether to use the IP of the server so that debrid download links always point to content that is close to the Comet server, or the IP of the client for 'cleaner' RD logging.

An alternative approach might be to only pass the client IP for non-proxied traffic and pass the Comet IP for proxied streams, or a configuration option to enable/disable this behaviour.

**Comment by npmstart-pray** [comment]
That seems a poor decision to me, implementing that. Is there a workaround to go back?

**Comment by funkypenguin** [comment]
Sending the client IP to RD is desirable, under normal circumstances (at least, that's been my experience of users requests). I agree that make it optional for proxystreaming makes sense too.

**Comment by g0ldyy** [comment]
I will just disable it completely for proxied streams.

**Comment by g0ldyy** [comment]
fixed.
