### ISSUE TITLE
Links generating in HTTP

### ISSUE THREAD

**Issue by Korgen0** [g0ldyy/comet#151]
When generating links in stremio it seems to be creating links for http, since I only accept connections to my reverse proxy under https the video errors as it can't load anything when it uses http. I temporarily am getting around this by setting up a 301 redirect on my reverse proxy to redirect http traffic to https, however I am still concerned that this is insecure. I am not sure how to get comet to generate links as https in the first place.

**Comment by g0ldyy** [comment]
configuration issue on your side.
not a Comet issue

**Comment by realtimey** [comment]
I've also run into this issue when running comet behind a HTTPS reverse proxy. The stream URLs returned are http:// only. What is the suggested way of setting comet to handle SSL?

**Comment by Korgen0** [comment]
I suspect maybe it is giving http links since internally my reverse proxy accesses comet through http on localhost, however even if I gave it a domain I'm not sure how to set up comet with ssl, how would this be done?

**Comment by Korgen0** [comment]
I keep looking through the config and I just can't figure out how this is a config error, comet just generates http:// links and gives them to stremio, ideally it should be generating them as https:// links
