### ISSUE TITLE
Add ability to filter out CAM and TeleSync

### ISSUE THREAD

**Issue by IrlJidel** [g0ldyy/comet#156]
Hi thanks for all the great updates.

Would it be possible to add filter options for CAM/TS ?

Thanks

**Comment by g0ldyy** [comment]
I'm not sure I understand how this would be useful
they are already ranked at the very bottom anyways

**Comment by IrlJidel** [comment]
If we extend that argument - why have filters for SD or any quality and just leave it to ranking/sorting.

Guess in this case it's really for the case when only results are CAM etc - would prefer if I got no results at all.as not interested

**Comment by g0ldyy** [comment]
done https://github.com/g0ldyy/comet/commit/fe3ddb6702aac23de8e3ad6b51c56899f3f3ea24, update Comet.
