### ISSUE TITLE
Feature request: Results per resolution

### ISSUE THREAD

**Issue by oleglucic** [g0ldyy/comet#158]
It would be nice if there was an option to limit the number of results per resolution than all results. This is because some resolutions have many streams and if you go with limiting to 10 links you wouldn't get all the resolutions but ones that fit in those 10 places. Example is torrentio which has this option. I hope the message isn't confusing. This feature would be soon nice to have : )

**Comment by Slyntax** [comment]
Agreed! Just found this due to Torrentio being down and after setting it up, this was the first feature I thought of.

**Comment by g0ldyy** [comment]
done https://github.com/g0ldyy/comet/commit/b2ecc867c0e5b05116e4079a495509f013f8766d
