### ISSUE TITLE
Using Mediaflow Proxy Instead of Warp

### ISSUE THREAD

**Issue by dimenzion-pm** [g0ldyy/comet#160]
I have a Mediaflow Proxy server that I would like to use instead of Warp. It'd be awesome to see more apps add this option. Thanks!

**Comment by g0ldyy** [comment]
wtf
wdym replace warp with mediaflow proxy this makes no sense
warp is not used to proxy the stream but to bypass Torrentio/RealDebrid/AllDebrid server blacklists which mediaflow proxy cannot do
comet already has its own stream proxy and mediaflow proxy will never be integrated as it is useless
