### ISSUE TITLE
Issue with Warp

### ISSUE THREAD

**Issue by DarthVitiate** [g0ldyy/comet#164]
Good evening,

I'm encountering an issue to use comet through warp proxy.

I've created a docker proxy network and I use Nginx as reverse proxy. I have another Stremio solution that works perfectly.
The .env file is properly filled as well.

Do you have any suggestion please?

Thank you for your help.

**Comment by g0ldyy** [comment]
what's the issue

**Comment by DarthVitiate** [comment]
Hi, Comet doesn’t stream through the proxy. Real debrid shows my real IP address. The warp container logs show nothing as well.

**Comment by g0ldyy** [comment]
> Hi, Comet doesn’t stream through the proxy. Real debrid shows my real IP address. The warp container logs show nothing as well.

what realdebrid shows is irrelevant, also the stream is not proxied through Warp : warp is only used to generate the download link

**Comment by DarthVitiate** [comment]
Hi, thank you for your answer.

I use one account for multiple users (and then different public IP adresses). My other add-on (Stream-Fusion) is forwarding all the traffic though the proxy, in order to avoid debriders bans

**Comment by g0ldyy** [comment]
flemme d'expliquer à quelqu'un qui comprend rien

**Comment by DarthVitiate** [comment]
C'est toi qui comprend rien, ça ne suffit pas ne générer le lien depuis le proxy. Il ne faut PAS qu'il y ait de streams simultanés avec deux IPs DIFFERENTES. Donc il faut proxifier également la diffusion. 
Go se soulager au bois de Boulogne mec.

**Comment by g0ldyy** [comment]
c'est bien ce que je dis tu comprends rien :)
