### ISSUE TITLE
Feature request: Nyaasi as a scrapper 

### ISSUE THREAD

**Issue by johnnyw94** [g0ldyy/comet#165]
Torrentio is the only one atm scrapes Nyaasi properly, but the addon is having issues now and then, so it would be really good as an alternative for anime sources if Nyaasi is added to comet

**Comment by g0ldyy** [comment]
Jackett is made for that :)

**Comment by johnnyw94** [comment]
> Jackett is made for that :)

The thing is I never seen a proper anime link showing up on Jackett community add-on or Jackettio add-on like the way Torrentio scrapes Nyaasi

**Comment by g0ldyy** [comment]
Torrentio have custom Nyaasi scraper.
anyone is welcome to PR a scraper for Comet!

**Comment by funkypenguin** [comment]
AFAIK none of the public jackett-based addons are configured for Nyaasi. You could try a [7-day free trial](https://store.elfhosted.com/product/comet) of a private Comet instance, with your own Jackett, and see if that does the job?
