### ISSUE TITLE
[request] Remove Cam , Telesync ,  Screener result in Comet+ RD

### ISSUE THREAD

**Issue by shanestonk** [g0ldyy/comet#167]
Hope there an option to filter out Cam, Telesync and Screener quality in Comet elfhost + RD

https://comet.elfhosted.com/

![image](https://github.com/user-attachments/assets/298c846e-20b7-4147-b08b-26cef5b2fcc3)

**Comment by IrlJidel** [comment]
This the same as https://github.com/g0ldyy/comet/issues/156 ?

**Comment by g0ldyy** [comment]
I'm not sure I understand how this would be useful
they are already ranked at the very bottom anyways

**Comment by g0ldyy** [comment]
done https://github.com/g0ldyy/comet/commit/fe3ddb6702aac23de8e3ad6b51c56899f3f3ea24, update Comet.
