### ISSUE TITLE
Can't get metadata for movies and shows

### ISSUE THREAD

**Issue by KvHx** [g0ldyy/comet#171]
I'm getting a comet error "can't get metadata for tt4270492" for the show Billions. I have to back out and select the show again to get links. It's also happening on other titles. Other addons are working. Is there something going on in the backend?![image](https://github.com/user-attachments/assets/ca5f46bf-5d1b-4886-aeb6-4df4b7ade796)

**Comment by g0ldyy** [comment]
send comet logs

**Comment by g0ldyy** [comment]
works fine for me, check if you can access https://v3.sg.media-imdb.com/suggestion/a/tt4270492.json with the machine you're running Comet with
