### ISSUE TITLE
Different IPs shown in Real debrid download stats when proxy is turned on

### ISSUE THREAD

**Issue by mahirdzirlo** [g0ldyy/comet#203]
Proxy turned on with proxy password and API key entered. Warp installed as well. I keep seeing different cloudflare addresses in real-debrid download server ip addresses. Wouldnt this cause a ban since it should be only one address (streaming server proxy IP address)?

104.28.192.67 and 104.28.192.61 are being shown.

**Comment by g0ldyy** [comment]
no, they don't care about the IPs on the dashboard (it's the IPs that generated a download link). they know what IP is downloading the file and warp is not used to download file in proxy mode.

**Comment by mahirdzirlo** [comment]
@g0ldyy how do one check what IP generated a download link?
