### ISSUE TITLE
Unable to install Comet Stremio addon from configuration page

### ISSUE THREAD

**Issue by mndubber** [g0ldyy/comet#213]
When attempting to configure and install Comet from https://comet.elfhosted.com/configure and using the 
"Install" button it opens the Stremio app and displays the following error:

![image](https://github.com/user-attachments/assets/655ee45c-7314-4721-a025-6708fab80683)

I have tried copying the URL and pasting in Stremio addon search bar as well which receives this error:

![image](https://github.com/user-attachments/assets/17377597-2bb8-4223-88b4-bcf18ee65030)

I previously had Comet working on this same Stremio application instance, but uninstalled due to RD premium expiring and generating a new RD API key.  Other addons were able to install properly, such as Torrentio.sh via the Stremio Addon "Community" tab.

**Comment by g0ldyy** [comment]
elfhosted reverse proxy issue
