### ISSUE TITLE
Support for uncached torrents for RD

### ISSUE THREAD

**Issue by xologram** [g0ldyy/comet#214]
In wake of new RD rules where cached files are no longer served, torrentio still is able to work with "Download to RD" feature. It does not know what is cached and what is not but still is able to play most of the stuff I tried. Any plans to include a feature like this to workaround new RD rules?

**Comment by Zaarrg** [comment]
Hey, im currently working on a fork / later on pull request, that will add uncached support for any indexer and debrid service.
The fork is [comet-uncached](https://github.com/Zaarrg/comet-uncached). Recently updated it to work with real debrid and torrentio uncached results. 

If you are interested u can take a look at that. Would be happy to receive feedback to find bugs faster.

(The fork still needs testing as only real debrid has full uncached support until im certain it works 99% as intended then other debrid services will be supported. There are some issue with the use of private trackers. But for torrentio this is no issue and it seems to work without a problem)

As for the setup, the only thing needed is to add torrentio into the env INDEXER_MANAGER_INDEXERS=["Torrentio"]. 
Then in the settings page u select torrentio under indexers uncached:
![image](https://github.com/user-attachments/assets/d89f3d22-c594-4f58-8e89-961b927bc896)

Also u can then deselect under resolutions "Uncached". This will allow the sorting by resolution or rank to work normally and prevent sorting everything into the "Uncached" resolution:
![image](https://github.com/user-attachments/assets/3442e4d5-8934-4464-b7a9-bb47491f24ba)

**Comment by xologram** [comment]
@Zaarrg you da man! I deployed it and so far looks like it's working. Regular comet shows nothing anymore for both RD and AD, elfhosted or selfhosted. Yours shows links and I was able to play couple of random links. Will run it for a while and report back if I see any issues!

thanks!
