### ISSUE TITLE
Reverse proxy configuration provides stream URL as non proxied IP

### ISSUE THREAD

**Issue by noobiangodd** [g0ldyy/comet#215]
When using a reverse proxy, when trying to play any streams, it provides the URL as https://localhost:8000 instead of the URL used to access Comet. This only happens when trying to play the stream, as searching through Stremio is using the correct URL.

**Comment by noobiangodd** [comment]
Done some digging and it seems to be related to this issue: https://github.com/encode/starlette/issues/604

**Comment by g0ldyy** [comment]
```
server {
    server_name example.com

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

config issue.
