### ISSUE TITLE
Alldebrid option for api doesn't work

### ISSUE THREAD

**Issue by Sovex666** [g0ldyy/comet#218]
Was using realdebrid with comet and now I switched to alldebrid and it seems that it doesn't pass any links to alldebrid, nothing shows on the download page on alldebrid
I'm using alldebrid with torentio with the same api key and it works there.
When I open a stream it just loads the subtitle then it dissapears.

**Comment by g0ldyy** [comment]
https://github.com/g0ldyy/comet/pull/217
+
alldebrid is overloaded atm
