### ISSUE TITLE
Search inside packs

### ISSUE THREAD

**Issue by marco-calautti** [g0ldyy/comet#230]
It seems that comet is not able to search for an episode/file, when this is part of a single torrent containing multiple files. Enabling this feature would drastically increase the number of hits when searching.

**Comment by g0ldyy** [comment]
it is able to.

**Comment by marco-calautti** [comment]
Strange, prowlar shows the links I want If I search directly with it, but comet finds nothing. I configured all indexers in comet as they are in prowlarr.

**Comment by marco-calautti** [comment]
It seems the problem is that comet does not search for the language. If I specify that I want a foreign language as a preferece, and show only that language in the results, comet does not find anything, while there are plenty of entries in that language.

Maybe the metadata of the torrent does not specify the language? In that case, it could be useful to also include the language tag (e.g., ger, ita, etc.) in the search query.

**Comment by g0ldyy** [comment]
imdb's api only returns the title in English so that's what we search
you're free to make a PR to support native languages with a no-ratelimit api 👍
