### ISSUE TITLE
Comet finds nothing now with RD, how to fix?

### ISSUE THREAD

**Issue by michael1900** [g0ldyy/comet#232]
Hey! Thanks before. I am using Comet wirh RD api key, the elfhosted public istance, but it finds nothing, no one result.
How to fix this?

Thank you again!

**Comment by michael1900** [comment]
No one?

**Comment by giorgi1324** [comment]
Likely direct cause of 
![realdebrid](https://github.com/user-attachments/assets/ff49d7f8-417c-47ae-b614-4f6b9a2cfb41)

Specifically `intantAvailability` endpoint has been killed and I see these log lines in my comet docker:
```
 realdebrid.get_instant - Exception while checking hash instant availability on Real-Debrid: 403, message='Forbidden', url='https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/....
 ```

**Comment by michael1900** [comment]
@giorgi1324 Yes, but the other addons has been fixed and now work well. So Comet will be fixed or we can forget it?

**Comment by michael1900** [comment]
> rewrite in progress.

Hi, sorry for question, but now the elf hosted version is updated? Or the rewrite is still in progress? Thank you

**Comment by g0ldyy** [comment]
still in progress
