### ISSUE TITLE
can add pikpak support ?

### ISSUE THREAD

**Issue by ericvlog** [g0ldyy/comet#3]
IT have 2 api , and i Found out now only mediafusion addons support.

if you can add , i give my account for test it.

**Comment by g0ldyy** [comment]
sure, send me an account and I will probably implement it when I have time!

discord: g_0ldy

**Comment by ericvlog** [comment]
hello, i already send friend request on discord.

thanks.

**Comment by g0ldyy** [comment]
accepted

**Comment by g0ldyy** [comment]
your account is no longer premium, I can't do my tests...
you got another one by any chance?

**Comment by ericvlog** [comment]
> your account is no longer premium, I can't do my tests... you got another one by any chance?

hello, same account now have 4 days premium ya.

**Comment by ericvlog** [comment]
hi developer, pikpak premium is expire, you still want premium for intergrade?

**Comment by g0ldyy** [comment]
> hi developer, pikpak premium is expire, you still want premium for apply?

hi, I can try today
just need a few hours of premium

**Comment by ericvlog** [comment]
> > hi developer, pikpak premium is expire, you still want premium for apply?
> 
> hi, I can try today
> just need a few hours of premium

Hi, it's already premium now. , 😀
