### ISSUE TITLE
Offcloud support as a debrid provider

### ISSUE THREAD

**Issue by ragmehos** [g0ldyy/comet#42]
Can you add offcloud as a debrid provider? Offcloud has a free trial where you can add 3 links and download that as well, and mediafusion has a reference to offcloud debrid provider as well as torrentio. Thanks.

**Comment by g0ldyy** [comment]
Hi,
I asked yesterday to their team for a premium API key as I need a lot more than 3 downloads to do my tests.

they still didn't reply

**Comment by g0ldyy** [comment]
if you can provide an account, I will make it

**Comment by ragmehos** [comment]
I'll try to get you one. Btw, I think with the current way comet is working, offcloud seems hard to make it fit and work. The reason is in get_files where you check for instant availability, offcloud doesnt provide any details other than the hash from the Offcloud API. So you do not get the information about the file, title, size, etc without adding the file to offcloud. Which means you need to add all the hashes before you can get any info out, which makes it useless. 

Any idea how to work around this to make it work with comet?

**Comment by g0ldyy** [comment]
hello, yes I tried yesterday with a premium account and their API is bullshit
not sure what I can do

**Comment by ragmehos** [comment]
Yeah, will just close this, seems quite hard to achieve it. Thanks for your time.
