### ISSUE TITLE
Zilean (DMM Scraper) support documentation

### ISSUE THREAD

**Issue by Varming73** [g0ldyy/comet#45]
I see that there is Zilean (DMM Scraper) support but can't find any documentation on how to set up Comet with Zilean..?

**Comment by g0ldyy** [comment]
check the .env-sample file
you just have to set your Zilean API url

**Comment by Varming73** [comment]
Copy that. Is your Elfhosted Comet instance using Zilean?

**Comment by g0ldyy** [comment]
yes it is
