### ISSUE TITLE
Configurations are not saved

### ISSUE THREAD

**Issue by xick** [g0ldyy/comet#53]
**_Issue:_** 
The comet instance configuration (languages, selected indexers, resolution, etc) seems like it doesn't persist or doesn't retrieve the previous data when clicking 'configure' from stremio.
**_Environment:_**
Both self-hosted and elfhosted public instance.
**_Reprodution Steps_**
- Make modifications of the instance from https://comet.elfhosted.com/configure or selfhosted page. Select 'install' or generate link.
- Once installed on stremio, click on 'configure'. 
- You should now retrieve the custom configuration, instead the default one is displayed.

**Comment by g0ldyy** [comment]
yes, I didn't have time to integrate this feature to the webui unfortunately

It will probably be added soon but all contributions are appreciated if someone wants to take a look :D

**Comment by xick** [comment]
Oh makes sense, so basically they're just placeholder for now.I could take a look on spare time, but first I have to figure out why I'm getting tons of hash exceptions when using prowlarr and custom indexers. I mean, that happens only on torrents with lot of results, could be a rate limit from the indexer itself, but that doesn't make sense as prowlarr  it's throwing away all  the good results if found a single exception. I could open a separate Issue for that.Il giorno 18 lug 2024, alle ore 08:13, Goldy ***@***.***> ha scritto:﻿
yes, I didn't have time to integrate this feature to the webui unfortunately
It will probably be added soon but all contributions are appreciated if someone wants to take a look :D

**Comment by g0ldyy** [comment]
> Oh makes sense, so basically they're just placeholder for now. I could take a look on spare time, but first I have to figure out why I'm getting tons of hash exceptions when using prowlarr and custom indexers. I mean, that happens only on torrents with lot of results, could be a rate limit from the indexer itself, but that doesn't make sense as  it's throwing away all  the good results if found a single exception. I could open a separate Issue for that.

https://github.com/g0ldyy/comet/issues/44#issuecomment-2227237740
it is indeed a ratelimit
if one fails, it shouldn't affect the others though since each hash info retrieval is in a separate "thread" though
Could you send me the logs / errors so that I can try to determine if there's a problem?

**Comment by xick** [comment]
Closed with PR https://github.com/g0ldyy/comet/pull/63
