### ISSUE TITLE
more options

### ISSUE THREAD

**Issue by BlackListedGhosTY** [g0ldyy/comet#60]
hi. how can get more options? 
![image](https://github.com/user-attachments/assets/4c49741b-9763-4d21-ba32-1f8a0a20ce8d)
currently im only getting this few 
![image](https://github.com/user-attachments/assets/03b17d46-fcf8-4e0b-80b0-752cc85bb31c)

**Comment by g0ldyy** [comment]
you have to host your own Comet instance if you want to add more indexers

**Comment by funkypenguin** [comment]
Or, you know... https://elfhosted.com/app/comet/ :)

**Comment by BlackListedGhosTY** [comment]
thanks for help
