### ISSUE TITLE
Feature req: Sort output

### ISSUE THREAD

**Issue by Varming73** [g0ldyy/comet#68]
It would be really great if we could sort the output like for example KnightCrawler and Torrentio.

**Comment by g0ldyy** [comment]
Torrentio ranking is "dumb"
Sort by size is useless (size  != quality)
But yes I will add these options soon because most people will never understand.

There will also be a space on the WebUI to configure the Smart Ranking in a very complex and precise way.

**Comment by Varming73** [comment]
Sort by size is useless (size != quality) - I fully agree but sorting by resolution would be nice though.

**Comment by xick** [comment]
If I can say my word, I would find useful sort results for languages, e.g displaying torrents in a preferred language first

**Comment by utkarshsethi** [comment]
@Zaarrg seems to already be working for sort by quality and a few other features in his fork.

**Comment by utkarshsethi** [comment]
@Zaarrg sorting by resolution works but selecting resolution & seeders leads to exceptions.

logs: https://pastebin.com/MiPcDtAC

**Comment by Zaarrg** [comment]
@utkarshsethi Updated the image. Sorting should work now, also fixed the file extension missing when comet would load from the cache.
