### ISSUE TITLE
CORS allow origin not matching origin error while using browser version of stremio

### ISSUE THREAD

**Issue by tarandeepbrar** [g0ldyy/comet#95]
I am self hosting and have setup comet to support real debrid proxy streaming. If I use the stremio **android** app, I can see links to stream from both torrentio and comet. And when I stream through comet, it proxies the stream through my self-hosted server as expected. But when I try doing the same through Windows/Ubuntu/MacOs clients, I don't get any comet streams(I only get torrentio streams). After troubleshooting using the web browser, I found that the api requests are failing with "CORS allow origin not matching origin" error. Upon further investigation I found that the response header from comet contains 2 values for "access-control-allow-origin" where there should be 1.

```
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-credentials: true
access-control-allow-origin: <MYDOMAIN>
access-control-allow-origin: https://web.stremio.com
content-security-policy: frame-ancestors 'self'
content-type: application/json
date: Sun, 11 Aug 2024 17:45:41 GMT
server: uvicorn
strict-transport-security: max-age=31536000; includeSubDomains
vary: Origin
x-content-type-options: nosniff
x-ratelimit-limit: 6000
x-ratelimit-remaining: 100
x-ratelimit-reset: 1723399541
x-served-by-cosmos: 1
x-timeout-duration: 4h0m0s
x-xss-protection: 1; mode=block
content-length: 6048
X-Firefox-Spdy: h2
```

After installing "CORS Everywhere" firefox extension, I was able to get the web version to load the list of available streams. Now when I try to play them, the requests are failing with NS_BINDING_ABORTED error. The comet logs don't contain any error.

**Comment by g0ldyy** [comment]
this is a configuration issue on your side, not a Comet issue.
