### ISSUE TITLE
return file extension and name as part of returned urls

### ISSUE THREAD

**Issue by utkarshsethi** [g0ldyy/comet#96]
Hi Comet returns the streams in the following format

`"url": "http://comet.<serverurl>.com/<base64 config data>/playback/<hash>/2"`

While Torrentio seems to do
`"url": "https://torrentio.strem.fun/realdebrid/APITOKEN/<hash>/null/1/<full file name>.mp4"`

The primary difference seems to be the lack of file extension, which results in iOS being unable to open the stream.

Is it possible to return the correct extensions which I'm hoping would fix iOS devices not being able to open the streams?

**Comment by g0ldyy** [comment]
can anyone confirm they can't run anything on IOS?

**Comment by utkarshsethi** [comment]
Along with the web player which is known to be bad on iOS. I've tried running the streams via VLC/outplayer and they still can't play them on iOS devices.

Have tested on 3 devices from different generations.

**Comment by utkarshsethi** [comment]
@Zaarrg do you have an updated `.env-sample` file? for the new indexer settings? Maybe I'm setting something wrong.

I'm using your docker image `ghcr.io/zaarrg/comet-uncached:latest` but I'm still not getting the file extension as part of the returned URL.


logs: https://pastebin.com/QpVGiiKN

**Comment by utkarshsethi** [comment]
@Zaarrg for #68 sorting by resolution works but selecting resolution>seeders leads to exceptions.

logs: https://pastebin.com/MiPcDtAC

**Comment by g0ldyy** [comment]
works fine without this on my IOS.
